### ISSUE TITLE
Crashes in 0.21

### ISSUE THREAD

**Issue by FunshineX** [rafacost/TheLangoliers#3]
Need to update to the latest version of ex-nihilo, forestry and compact machines to prevent two crash issues (similar error for both crashes):

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
	at forestry.core.fluids.TankManager.processGuiUpdate(TankManager.java:221)
	at forestry.core.gui.ContainerLiquidTanks.func_75137_b(ContainerLiquidTanks.java:87)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by rafacost** [comment]
Updated a bunch of mods, tested this issue, and it seems that its fixed!
